var OA_output = new Array(); 
OA_output['1'] = '';
OA_output['1'] += "<"+"script async src=\"//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js\"><"+"/script>\n";
OA_output['1'] += "<"+"!-- 侧栏矩形 -->\n";
OA_output['1'] += "<"+"ins class=\"adsbygoogle\"\n";
OA_output['1'] += "style=\"display:inline-block;width:255px;height:213px\"\n";
OA_output['1'] += "data-ad-client=\"ca-pub-6330872677300335\"\n";
OA_output['1'] += "data-ad-slot=\"9674628595\"><"+"/ins>\n";
OA_output['1'] += "<"+"script>\n";
OA_output['1'] += "(adsbygoogle = window.adsbygoogle || []).push({});\n";
OA_output['1'] += "<"+"/script><"+"div id=\'beacon_fe9186a929\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=1&amp;campaignid=1&amp;zoneid=1&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fblog%2Fadd&amp;referer=https%3A%2F%2Fsegmentfault.com%2Fwrite%3Ffreshman%3D1&amp;cb=fe9186a929\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['2'] = '';
OA_output['2'] += "<"+"div id=\'beacon_71b7f99d92\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=0&amp;campaignid=0&amp;zoneid=2&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fblog%2Fadd&amp;referer=https%3A%2F%2Fsegmentfault.com%2Fwrite%3Ffreshman%3D1&amp;cb=71b7f99d92\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['3'] = '';
OA_output['3'] += "<"+"div id=\'beacon_d66f7e766b\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=0&amp;campaignid=0&amp;zoneid=3&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fblog%2Fadd&amp;referer=https%3A%2F%2Fsegmentfault.com%2Fwrite%3Ffreshman%3D1&amp;cb=d66f7e766b\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['4'] = '';
OA_output['4'] += "<"+"div style=\"text-align: center; line-height: 0; background: #FAFAFA;\"><"+"script async src=\"//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js\"><"+"/script>\n";
OA_output['4'] += "<"+"!-- 自适应广告 -->\n";
OA_output['4'] += "<"+"ins class=\"adsbygoogle\"\n";
OA_output['4'] += "style=\"display:block\"\n";
OA_output['4'] += "data-ad-client=\"ca-pub-6330872677300335\"\n";
OA_output['4'] += "data-ad-slot=\"6644962961\"\n";
OA_output['4'] += "data-ad-format=\"auto\"\n";
OA_output['4'] += "data-full-width-responsive=\"true\"><"+"/ins>\n";
OA_output['4'] += "<"+"script>\n";
OA_output['4'] += "(adsbygoogle = window.adsbygoogle || []).push({});\n";
OA_output['4'] += "<"+"/script><"+"div id=\'beacon_a4c3d120d4\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=117&amp;campaignid=1&amp;zoneid=4&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fblog%2Fadd&amp;referer=https%3A%2F%2Fsegmentfault.com%2Fwrite%3Ffreshman%3D1&amp;cb=a4c3d120d4\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div><"+"/div>\n";
OA_output['5'] = '';
OA_output['5'] += "<"+"div id=\'beacon_6dce05cf69\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=0&amp;campaignid=0&amp;zoneid=5&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fblog%2Fadd&amp;referer=https%3A%2F%2Fsegmentfault.com%2Fwrite%3Ffreshman%3D1&amp;cb=6dce05cf69\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['6'] = '';
OA_output['6'] += "<"+"div id=\'beacon_ab4a4072ee\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=0&amp;campaignid=0&amp;zoneid=6&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fblog%2Fadd&amp;referer=https%3A%2F%2Fsegmentfault.com%2Fwrite%3Ffreshman%3D1&amp;cb=ab4a4072ee\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['7'] = '';
OA_output['7'] += "<"+"a href=\'https://sponsor.segmentfault.com/ck.php?oaparams=2__bannerid=56__zoneid=7__cb=b20f8da832__oadest=https%3A%2F%2Fsegmentfault.com%2Fls%2F1650000011318558\' target=\'_blank\'><"+"strong>大神的PHP 进阶之路<"+"/strong><"+"br>\n";
OA_output['7'] += "<"+"small style=\"color: #999\">亿级 PV 项目的架构梳理，性能提升实战<"+"/small><"+"/a><"+"div id=\'beacon_b20f8da832\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=56&amp;campaignid=14&amp;zoneid=7&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fblog%2Fadd&amp;referer=https%3A%2F%2Fsegmentfault.com%2Fwrite%3Ffreshman%3D1&amp;cb=b20f8da832\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['9'] = '';
OA_output['9'] += "<"+"a href=\'https://sponsor.segmentfault.com/ck.php?oaparams=2__bannerid=57__zoneid=9__cb=ac4addbc0f__oadest=https%3A%2F%2Fsegmentfault.com%2Fls%2F1650000011387052\' target=\'_blank\'><"+"strong> Java 微服务实践课<"+"/strong><"+"br>\n";
OA_output['9'] += "<"+"small style=\"color: #999\">上千人学习过的微服务实栈课<"+"/small><"+"/a><"+"div id=\'beacon_ac4addbc0f\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=57&amp;campaignid=14&amp;zoneid=9&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fblog%2Fadd&amp;referer=https%3A%2F%2Fsegmentfault.com%2Fwrite%3Ffreshman%3D1&amp;cb=ac4addbc0f\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['10'] = '';
OA_output['10'] += "<"+"div id=\'beacon_1ad9471cb0\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=0&amp;campaignid=0&amp;zoneid=10&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fblog%2Fadd&amp;referer=https%3A%2F%2Fsegmentfault.com%2Fwrite%3Ffreshman%3D1&amp;cb=1ad9471cb0\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['11'] = '';
OA_output['11'] += "<"+"div id=\'beacon_14f1c11e41\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=0&amp;campaignid=0&amp;zoneid=11&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fblog%2Fadd&amp;referer=https%3A%2F%2Fsegmentfault.com%2Fwrite%3Ffreshman%3D1&amp;cb=14f1c11e41\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['12'] = '';
OA_output['12'] += "<"+"div id=\'beacon_ff710da56c\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=0&amp;campaignid=0&amp;zoneid=12&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fblog%2Fadd&amp;referer=https%3A%2F%2Fsegmentfault.com%2Fwrite%3Ffreshman%3D1&amp;cb=ff710da56c\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['13'] = '';
OA_output['13'] += "<"+"div id=\'beacon_76fd8aaed3\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=0&amp;campaignid=0&amp;zoneid=13&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fblog%2Fadd&amp;referer=https%3A%2F%2Fsegmentfault.com%2Fwrite%3Ffreshman%3D1&amp;cb=76fd8aaed3\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['14'] = '';
OA_output['14'] += "<"+"div id=\'beacon_ceba331a64\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=0&amp;campaignid=0&amp;zoneid=14&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fblog%2Fadd&amp;referer=https%3A%2F%2Fsegmentfault.com%2Fwrite%3Ffreshman%3D1&amp;cb=ceba331a64\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['15'] = '';
OA_output['15'] += "<"+"div id=\'beacon_d11738f7b3\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=0&amp;campaignid=0&amp;zoneid=15&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fblog%2Fadd&amp;referer=https%3A%2F%2Fsegmentfault.com%2Fwrite%3Ffreshman%3D1&amp;cb=d11738f7b3\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['16'] = '';
OA_output['16'] += "<"+"div id=\'beacon_cd526445e4\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=0&amp;campaignid=0&amp;zoneid=16&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fblog%2Fadd&amp;referer=https%3A%2F%2Fsegmentfault.com%2Fwrite%3Ffreshman%3D1&amp;cb=cd526445e4\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['17'] = '';
OA_output['17'] += "<"+"div id=\'beacon_8ee22e5339\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=0&amp;campaignid=0&amp;zoneid=17&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fblog%2Fadd&amp;referer=https%3A%2F%2Fsegmentfault.com%2Fwrite%3Ffreshman%3D1&amp;cb=8ee22e5339\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
