var OA_output = new Array(); 
OA_output['1'] = '';
OA_output['1'] += "<"+"script async src=\"//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js\"><"+"/script>\n";
OA_output['1'] += "<"+"!-- 侧栏矩形 -->\n";
OA_output['1'] += "<"+"ins class=\"adsbygoogle\"\n";
OA_output['1'] += "style=\"display:inline-block;width:255px;height:213px\"\n";
OA_output['1'] += "data-ad-client=\"ca-pub-6330872677300335\"\n";
OA_output['1'] += "data-ad-slot=\"9674628595\"><"+"/ins>\n";
OA_output['1'] += "<"+"script>\n";
OA_output['1'] += "(adsbygoogle = window.adsbygoogle || []).push({});\n";
OA_output['1'] += "<"+"/script><"+"div id=\'beacon_8c10e502b1\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=1&amp;campaignid=1&amp;zoneid=1&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fa%2F1190000018425629&amp;referer=https%3A%2F%2Fsegmentfault.com%2F&amp;cb=8c10e502b1\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['2'] = '';
OA_output['2'] += "<"+"div style=\"padding: 10px 0; line-height: 0; background: #EEE\">\n";
OA_output['2'] += "<"+"div class=\"container text-center\" style=\"position: relative;\">\n";
OA_output['2'] += "<"+"a href=\"https://segmentfault.com/user/login\" class=\"small text-muted\" style=\"position: absolute; top: 10px; right: 15px;\">登录免广告<"+"/a><"+"script async src=\"//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js\"><"+"/script>\n";
OA_output['2'] += "<"+"!-- 大型页首横幅 -->\n";
OA_output['2'] += "<"+"ins class=\"adsbygoogle\"\n";
OA_output['2'] += "style=\"display:inline-block;width:970px;height:90px\"\n";
OA_output['2'] += "data-ad-client=\"ca-pub-6330872677300335\"\n";
OA_output['2'] += "data-ad-slot=\"6450634185\"><"+"/ins>\n";
OA_output['2'] += "<"+"script>\n";
OA_output['2'] += "(adsbygoogle = window.adsbygoogle || []).push({});\n";
OA_output['2'] += "<"+"/script><"+"div id=\'beacon_93d35a3869\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=43&amp;campaignid=1&amp;zoneid=2&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fa%2F1190000018425629&amp;referer=https%3A%2F%2Fsegmentfault.com%2F&amp;cb=93d35a3869\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div><"+"/div>\n";
OA_output['2'] += "<"+"/div>\n";
OA_output['3'] = '';
OA_output['3'] += "<"+"div style=\"text-align: center; line-height: 0; background: #EEE\"><"+"script async src=\"//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js\"><"+"/script>\n";
OA_output['3'] += "<"+"!-- 中部横幅广告位 -->\n";
OA_output['3'] += "<"+"ins class=\"adsbygoogle\"\n";
OA_output['3'] += "style=\"display:inline-block;width:728px;height:90px\"\n";
OA_output['3'] += "data-ad-client=\"ca-pub-6330872677300335\"\n";
OA_output['3'] += "data-ad-slot=\"5598290435\"><"+"/ins>\n";
OA_output['3'] += "<"+"script>\n";
OA_output['3'] += "(adsbygoogle = window.adsbygoogle || []).push({});\n";
OA_output['3'] += "<"+"/script><"+"div id=\'beacon_f4c6e08f2d\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=2&amp;campaignid=1&amp;zoneid=3&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fa%2F1190000018425629&amp;referer=https%3A%2F%2Fsegmentfault.com%2F&amp;cb=f4c6e08f2d\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div><"+"/div>\n";
OA_output['4'] = '';
OA_output['4'] += "<"+"div id=\'beacon_81c301d4e3\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=0&amp;campaignid=0&amp;zoneid=4&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fa%2F1190000018425629&amp;referer=https%3A%2F%2Fsegmentfault.com%2F&amp;cb=81c301d4e3\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['5'] = '';
OA_output['5'] += "<"+"div id=\'beacon_53f5ff0e8f\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=0&amp;campaignid=0&amp;zoneid=5&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fa%2F1190000018425629&amp;referer=https%3A%2F%2Fsegmentfault.com%2F&amp;cb=53f5ff0e8f\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['6'] = '';
OA_output['6'] += "<"+"div id=\'beacon_351b077b97\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=0&amp;campaignid=0&amp;zoneid=6&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fa%2F1190000018425629&amp;referer=https%3A%2F%2Fsegmentfault.com%2F&amp;cb=351b077b97\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['7'] = '';
OA_output['7'] += "<"+"a href=\'https://sponsor.segmentfault.com/ck.php?oaparams=2__bannerid=57__zoneid=7__cb=94bfa834f6__oadest=https%3A%2F%2Fsegmentfault.com%2Fls%2F1650000011387052\' target=\'_blank\'><"+"strong> Java 微服务实践课<"+"/strong><"+"br>\n";
OA_output['7'] += "<"+"small style=\"color: #999\">上千人学习过的微服务实栈课<"+"/small><"+"/a><"+"div id=\'beacon_94bfa834f6\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=57&amp;campaignid=14&amp;zoneid=7&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fa%2F1190000018425629&amp;referer=https%3A%2F%2Fsegmentfault.com%2F&amp;cb=94bfa834f6\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['9'] = '';
OA_output['9'] += "<"+"a href=\'https://sponsor.segmentfault.com/ck.php?oaparams=2__bannerid=56__zoneid=9__cb=d8dc812d3a__oadest=https%3A%2F%2Fsegmentfault.com%2Fls%2F1650000011318558\' target=\'_blank\'><"+"strong>大神的PHP 进阶之路<"+"/strong><"+"br>\n";
OA_output['9'] += "<"+"small style=\"color: #999\">亿级 PV 项目的架构梳理，性能提升实战<"+"/small><"+"/a><"+"div id=\'beacon_d8dc812d3a\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=56&amp;campaignid=14&amp;zoneid=9&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fa%2F1190000018425629&amp;referer=https%3A%2F%2Fsegmentfault.com%2F&amp;cb=d8dc812d3a\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['10'] = '';
OA_output['10'] += "<"+"div id=\'beacon_4dccfde4d6\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=0&amp;campaignid=0&amp;zoneid=10&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fa%2F1190000018425629&amp;referer=https%3A%2F%2Fsegmentfault.com%2F&amp;cb=4dccfde4d6\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['11'] = '';
OA_output['11'] += "<"+"div id=\'beacon_e4dac8239d\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=0&amp;campaignid=0&amp;zoneid=11&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fa%2F1190000018425629&amp;referer=https%3A%2F%2Fsegmentfault.com%2F&amp;cb=e4dac8239d\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['12'] = '';
OA_output['12'] += "<"+"div id=\'beacon_2ed0e61fdc\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=0&amp;campaignid=0&amp;zoneid=12&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fa%2F1190000018425629&amp;referer=https%3A%2F%2Fsegmentfault.com%2F&amp;cb=2ed0e61fdc\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['13'] = '';
OA_output['13'] += "<"+"div id=\'beacon_c9dbf9f331\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=0&amp;campaignid=0&amp;zoneid=13&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fa%2F1190000018425629&amp;referer=https%3A%2F%2Fsegmentfault.com%2F&amp;cb=c9dbf9f331\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['14'] = '';
OA_output['14'] += "<"+"div id=\'beacon_ee4253c205\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=0&amp;campaignid=0&amp;zoneid=14&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fa%2F1190000018425629&amp;referer=https%3A%2F%2Fsegmentfault.com%2F&amp;cb=ee4253c205\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['15'] = '';
OA_output['15'] += "<"+"div id=\'beacon_af5bb8bde5\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=0&amp;campaignid=0&amp;zoneid=15&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fa%2F1190000018425629&amp;referer=https%3A%2F%2Fsegmentfault.com%2F&amp;cb=af5bb8bde5\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['16'] = '';
OA_output['16'] += "<"+"div id=\'beacon_50ab0fb112\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=0&amp;campaignid=0&amp;zoneid=16&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fa%2F1190000018425629&amp;referer=https%3A%2F%2Fsegmentfault.com%2F&amp;cb=50ab0fb112\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['17'] = '';
OA_output['17'] += "<"+"div id=\'beacon_97e676110a\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=0&amp;campaignid=0&amp;zoneid=17&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fa%2F1190000018425629&amp;referer=https%3A%2F%2Fsegmentfault.com%2F&amp;cb=97e676110a\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
