var OA_output = new Array(); 
OA_output['1'] = '';
OA_output['1'] += "<"+"script async src=\"//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js\"><"+"/script>\n";
OA_output['1'] += "<"+"!-- 侧栏矩形 -->\n";
OA_output['1'] += "<"+"ins class=\"adsbygoogle\"\n";
OA_output['1'] += "style=\"display:inline-block;width:255px;height:213px\"\n";
OA_output['1'] += "data-ad-client=\"ca-pub-6330872677300335\"\n";
OA_output['1'] += "data-ad-slot=\"9674628595\"><"+"/ins>\n";
OA_output['1'] += "<"+"script>\n";
OA_output['1'] += "(adsbygoogle = window.adsbygoogle || []).push({});\n";
OA_output['1'] += "<"+"/script><"+"div id=\'beacon_ea35370454\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=1&amp;campaignid=1&amp;zoneid=1&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fhottest&amp;referer=http%3A%2F%2Flocalhost%3A8080%2Fquery&amp;cb=ea35370454\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['2'] = '';
OA_output['2'] += "<"+"div id=\'beacon_87bc333e3b\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=0&amp;campaignid=0&amp;zoneid=2&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fhottest&amp;referer=http%3A%2F%2Flocalhost%3A8080%2Fquery&amp;cb=87bc333e3b\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['3'] = '';
OA_output['3'] += "<"+"div id=\'beacon_af85bc5518\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=0&amp;campaignid=0&amp;zoneid=3&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fhottest&amp;referer=http%3A%2F%2Flocalhost%3A8080%2Fquery&amp;cb=af85bc5518\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['4'] = '';
OA_output['4'] += "<"+"div id=\'beacon_ff88c0f8d2\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=0&amp;campaignid=0&amp;zoneid=4&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fhottest&amp;referer=http%3A%2F%2Flocalhost%3A8080%2Fquery&amp;cb=ff88c0f8d2\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['5'] = '';
OA_output['5'] += "<"+"div id=\'beacon_9b47b4ec12\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=0&amp;campaignid=0&amp;zoneid=5&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fhottest&amp;referer=http%3A%2F%2Flocalhost%3A8080%2Fquery&amp;cb=9b47b4ec12\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['6'] = '';
OA_output['6'] += "<"+"div id=\'beacon_e623d1b971\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=0&amp;campaignid=0&amp;zoneid=6&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fhottest&amp;referer=http%3A%2F%2Flocalhost%3A8080%2Fquery&amp;cb=e623d1b971\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['7'] = '';
OA_output['7'] += "<"+"a href=\'https://sponsor.segmentfault.com/ck.php?oaparams=2__bannerid=56__zoneid=7__cb=a9c1ff8df3__oadest=https%3A%2F%2Fsegmentfault.com%2Fls%2F1650000011318558\' target=\'_blank\'><"+"strong>大神的PHP 进阶之路<"+"/strong><"+"br>\n";
OA_output['7'] += "<"+"small style=\"color: #999\">亿级 PV 项目的架构梳理，性能提升实战<"+"/small><"+"/a><"+"div id=\'beacon_a9c1ff8df3\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=56&amp;campaignid=14&amp;zoneid=7&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fhottest&amp;referer=http%3A%2F%2Flocalhost%3A8080%2Fquery&amp;cb=a9c1ff8df3\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['9'] = '';
OA_output['9'] += "<"+"a href=\'https://sponsor.segmentfault.com/ck.php?oaparams=2__bannerid=57__zoneid=9__cb=088b99ff2f__oadest=https%3A%2F%2Fsegmentfault.com%2Fls%2F1650000011387052\' target=\'_blank\'><"+"strong> Java 微服务实践课<"+"/strong><"+"br>\n";
OA_output['9'] += "<"+"small style=\"color: #999\">上千人学习过的微服务实栈课<"+"/small><"+"/a><"+"div id=\'beacon_088b99ff2f\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=57&amp;campaignid=14&amp;zoneid=9&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fhottest&amp;referer=http%3A%2F%2Flocalhost%3A8080%2Fquery&amp;cb=088b99ff2f\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['10'] = '';
OA_output['10'] += "<"+"div id=\'beacon_a75dfc1601\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=0&amp;campaignid=0&amp;zoneid=10&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fhottest&amp;referer=http%3A%2F%2Flocalhost%3A8080%2Fquery&amp;cb=a75dfc1601\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['11'] = '';
OA_output['11'] += "<"+"div id=\'beacon_88e1bab4bd\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=0&amp;campaignid=0&amp;zoneid=11&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fhottest&amp;referer=http%3A%2F%2Flocalhost%3A8080%2Fquery&amp;cb=88e1bab4bd\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['12'] = '';
OA_output['12'] += "<"+"div id=\'beacon_bc42afcb29\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=0&amp;campaignid=0&amp;zoneid=12&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fhottest&amp;referer=http%3A%2F%2Flocalhost%3A8080%2Fquery&amp;cb=bc42afcb29\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['13'] = '';
OA_output['13'] += "<"+"div id=\'beacon_b4e6efda4a\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=0&amp;campaignid=0&amp;zoneid=13&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fhottest&amp;referer=http%3A%2F%2Flocalhost%3A8080%2Fquery&amp;cb=b4e6efda4a\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['14'] = '';
OA_output['14'] += "<"+"div id=\'beacon_5f28fb62de\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=0&amp;campaignid=0&amp;zoneid=14&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fhottest&amp;referer=http%3A%2F%2Flocalhost%3A8080%2Fquery&amp;cb=5f28fb62de\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['15'] = '';
OA_output['15'] += "<"+"div id=\'beacon_56e125fb40\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=0&amp;campaignid=0&amp;zoneid=15&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fhottest&amp;referer=http%3A%2F%2Flocalhost%3A8080%2Fquery&amp;cb=56e125fb40\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['16'] = '';
OA_output['16'] += "<"+"div id=\'beacon_b70e11a20b\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=0&amp;campaignid=0&amp;zoneid=16&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fhottest&amp;referer=http%3A%2F%2Flocalhost%3A8080%2Fquery&amp;cb=b70e11a20b\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['17'] = '';
OA_output['17'] += "<"+"div id=\'beacon_51c87bb03f\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=0&amp;campaignid=0&amp;zoneid=17&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fhottest&amp;referer=http%3A%2F%2Flocalhost%3A8080%2Fquery&amp;cb=51c87bb03f\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
